config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {registrations: 'members/registrations' ,omniauth_callbacks: 'members/omniauth_callbacks' }
  resource :member, only: :show do
    member do
      get :following, :followers
      get :foodday,:foodmonth,:foodweek  # food record by day/week/month
      get :sportday,:sportmonth,:sportweek  # sport record by day/week/month
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :blogs  do 
    member do 
       patch :tdee   #/blog/:id/tdee
       get   :secret #/blog/:id/secret
    end
  end
  

  resources :records
  root 'records#index'
  resources :users
  resources :record_databases
  resources :exercise_records
  resources :food_records
  resources :demands


  post '/search_sport/favorite' => 'exercise_records#favorite', :as => 'favorite_exercise_record' 
  post '/search_food/favorite' => 'food_records#favorite', :as => 'favorite_food_record' 
  get '/search_sport/statistics' => 'exercise_records#statistics', :as => 'statistics_exercise_record'
  get '/search_food/statistics' => 'food_records#statistics', :as => 'statistics_food_record'
  get '/search_food' => 'record_databases#search_food', :as => 'search_food_record_database'
  get '/search_sport' => 'record_databases#search_sport', :as => 'search_sport_record_database'
  get '/search_food/random' => 'food_records#random', :as => 'random_food_record'
  get '/search_food/list' => 'food_records#list', :as => 'list_food_record'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_member!
  def index
    @member = Member.order(created_at: :asc).with_attached_cover_image
  end

  def show
    start_time = Time.zone.now.beginning_of_day
    end_time = Time.zone.now.end_of_day

    @following = Member.find(params[:id]).following
    @followers = Member.find(params[:id]).followers

    @member = Member.find(params[:id])
    @foods_today = FoodRecord.where(member_id: @member.id).where('created_at BETWEEN ? AND ?', start_time, end_time)
    @calories = []
    @foods_today.each do |f|
      @calories << f['calories']
    end

    @sports = SportRecord.where(member_id: @member.id).where('created_at BETWEEN ? AND ?', start_time, end_time)
    @sprot_calories = []
    @sports.each do |s|
      @sprot_calories << s['totalconsum']
    end
  end
end

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="row row-cols-1 row-cols-md-4 mt-2">
      <% @member.each do |m| %>
        <% if m != current_member %>
          <div class="col mb-4">
            <div class="card">
              <div class="card-image">
                <% if m.cover_image.attached? %>
                  <%= image_tag m.cover_image.variant(resize_to_limit: [300, 300]), class:'card-image' %>
                <% else %>
                  <img src="https://picsum.photos/300/300/?random=23", class="card-image">
                <% end %>
                <%= link_to '詳細資訊', user_path(m), class:'txt h2' %>
              </div>
              <div class="card-body">
                <% if m.name? %>
                  <%= link_to m.name, user_path(m), class:'text-info' %>
                <% else %>
                  <%= link_to m.email, user_path(m), class:'text-info' %>
                <% end %>
                <% if current_member.following?(m) %>
                  <%= link_to relationship_path(m), remote: true ,method: :delete, 'pos-id': m.id, class: 'follow-red' do%>
                  <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to relationships_path(followed_id: m.id), remote: true ,method: :post, 'pos-id': m.id, class: 'follow-gray' do%>
                  <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="container">
  <div class="row show-title">
    <div class="col-12 col-md-12">
      <div class="mt-md-3 mb-md-5">
        <div class="d-flex mb-3 mt-3 justify-content-md-start">
          <% if @member.cover_image.attached? %>
            <%= image_tag @member.cover_image.variant(resize_to_limit: [300, 300]), class:'rounded-circle show-img' %>
          <% else %>
            <img src="https://picsum.photos/50/50/?random=34" class="rounded-circle show-img"> 
          <% end %>
          <div>
            <div class="mb-md-3 m-auto">
              <div class="row no-gutters">
                <div class="col-md-12">
                  <div class="show-body">
                    <div class="d-md-flex">
                      <h5 class="h5 font-weight-bold mt-md-2 ml-md-1">
                        <% if @member.name? %>
                          <%= @member.name %>
                        <% else %>
                          NoName
                        <% end %>
                      </h5>
                    <span class="ml-md-1"><%= render 'shared/states' %></span>
                      <%= render 'members/follow_form' %>
                    </div>
                    <p class="card-text"></p>
                    <p class="card-text"><small class="text-muted"></small></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6"></div>
  </div>
</div>
<div class="container">
  <div class="row d-flex justify-content-center m-auto">
    <div class="col-12 col-md-6 mb-md-5 mt-3">
      <span class="h2">攝取比例&ensp;<i class="fas fa-chart-pie"></i></span>
      <div>
        <canvas id="heyChart"></canvas>
      </div>
      <script>
        var ctx = document.getElementById("heyChart");
        var myChart = new Chart(ctx, {
          type: 'pie',
          data: {
            labels: ["攝取熱量", "運動消耗"],
            datasets: [{
              label: ['消耗'],
              data: [
                '<%= @calories.sum %>',
                '<%= @sprot_calories.sum %>',
            ],
              backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)'
              ],
              borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)'
              ],
              borderWidth: 1
            }]
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero:true,
                }
              }]
            }
          }
        });
      </script> 
    </div> 
    <div class="col-12 col-md-6 show-food mt-3">
      <div class="collapse show" id="foodsExample">
        <div class="h3">今日飲食紀錄&ensp;<i class="fas fa-utensils"></i></div>
        <li>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">名稱</th>
                <th scope="col">熱量</th>
                <th scope="col">時間</th>
              </tr>
            </thead>
              <tbody>
                <% @foods_today.each do |f| %>
                  <tr>
                    <td scopr="col"><%= f.name %></td>
                    <td scopr="col"><%= f.calories %></td>
                    <td scope="col"><%= f.created_at.strftime("%T") %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </li>
      </div>
      <div class="collapse show" id="sportsExample">
        <div class="h3">今日運動紀錄&ensp;<i class="fas fa-running"></i></div>
        <li>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">名稱</th>
                <th scope="col">時間</th>
                <th scope="col">消耗</th>
              </tr>
            </thead>
              <tbody>
                <% @sports.each do |s| %>
                  <tr>
                    <td scopr="col"><%= s.name %></td>
                    <td scope="col"><%= s.min %></td>
                    <td scope="col"><%= s.totalconsum %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </li>
      </div>
    </div>
  </div>
</div>