config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {registrations: 'members/registrations' ,omniauth_callbacks: 'members/omniauth_callbacks' }
  resource :member, only: :show do
    member do
      get :following, :followers
      get :foodday,:foodmonth,:foodweek  # food record by day/week/month
      get :sportday,:sportmonth,:sportweek  # sport record by day/week/month
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :blogs  do 
    member do 
       patch :tdee   #/blog/:id/tdee
       get   :secret #/blog/:id/secret
    end
  end
  

  resources :records
  root 'records#index'
  resources :users
  resources :record_databases
  resources :exercise_records
  resources :food_records
  resources :demands


  post '/search_sport/favorite' => 'exercise_records#favorite', :as => 'favorite_exercise_record' 
  post '/search_food/favorite' => 'food_records#favorite', :as => 'favorite_food_record' 
  get '/search_sport/statistics' => 'exercise_records#statistics', :as => 'statistics_exercise_record'
  get '/search_food/statistics' => 'food_records#statistics', :as => 'statistics_food_record'
  get '/search_food' => 'record_databases#search_food', :as => 'search_food_record_database'
  get '/search_sport' => 'record_databases#search_sport', :as => 'search_sport_record_database'
  get '/search_food/random' => 'food_records#random', :as => 'random_food_record'
  get '/search_food/list' => 'food_records#list', :as => 'list_food_record'
end

app/controllers/record_databases_controller.rb
class RecordDatabasesController < ApplicationController
    def index
    end
  
    def show
    end
  
    def new
    end
  
    def edit
    end

    def create
    end

  
    def updata
    end
  
    def destroy
    end

    def search_food

        @search_food = params["search_food"]
        @food_databases = []
        #---------------------------------------
        if current_member.present?
          @record_foods = FoodRecord.where(member_id: current_member.id, created_at: (Time.now.midnight)..(Time.now))
          food_sum
          @current_user_secret = Membersecret.find_by( member_id: current_member.id)
          if @search_food.present?
            @food_databases = FoodDatabase.where("name ILIKE ?", "%#{@search_food}%")            
            respond_to do |format|
              format.json { render json: @food_databases}
              format.html { render :search_food}
           end
          else
          end
        else       
        end
    end

    def search_sport
      @search_sport = params["search_sport"]
      @sports = []
      if @search_sport.present?
          @sports= Sport.where("name ILIKE ?", "%#{@search_sport}%")
          respond_to do |format|
            format.json { render json: @sports}
            format.html { render :search_sport }
          end      
      else 
      end
      
      daily_sport = params["member_id"]
      if daily_sport.present?
        @record_sports = SportRecord.where(member_id: params[:member_id], created_at: (Time.now.midnight)..(Time.now))  
          
        respond_to do |format|
          format.json { render json: @record_sports}
          format.html { render :search_sport }
        end  
      else
      end
    end
     
    private 

    def food_sum
        @sum=0
        @record_foods.each do |record_food|
        @sum = @sum + record_food.total_calorie
     end
    end
end

app/views/record_databases/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Daily record</title>
</head>
<body>
     <a href="">History record</a>
     <button type="button">Add New Record</button>
     <button type="button">Add New Food Record</button>
</body>
</html>

app/views/record_databases/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Daily record</title>
</head>
<body>
     <a href="">History record</a>
     <div class="container">
           <input type="text" placeholder="Type your food">
     <button type="submit">Add New Record</button>
     <button type="button">Add New Food Record</button>    
     </div>

</body>
</html>

app/views/record_databases/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Daily record</title>
</head>
<body>
     <a href="">History record</a>
     <div class="container">
    <button type="button">Add New Record</button>
     <button type="button">Add New Food Record</button>
   
     </div>
</body>
</html>

app/views/record_databases/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search Data</title>
</head>
<body>

    <div class="container">
    
        <div class="row">
          <div class="col-xs-12 col-sm-8 offset-sm-2">
            <h1>Food Calorie</h1>
            
            <%= form_tag search_record_database_path, :method => 'get' do %>
            <%= text_field_tag :search, @search %></h3>
            <%= submit_tag "Search" %>
            <% end %>


            <% @food_databases.each do |food_database| %>
            <h3> 食物名稱:<%= food_database.name %></h3>
            <p>　卡洛里：<%= food_database.calories %></p>
            <p>　蛋白質：<%= food_database.protein %></p>
            <p>　體脂肪: <%= food_database.fat_content %></p>
            <p>  碳水化合物: <%= food_database.carbohydrate %></p>
            <% end %>

          </div>
        </div>
      </div>

    

      
</body>
</html>

app/views/record_databases/search_sport.erb
 <section class="section sport" id="sport">
  <div class="container-fluid" >
    <div class="row full">
      <div class="col-md-6 select-sport">
        <div class="col-md-6 mb-3 sport_usr_name ">
         <div class="sport-user-name">
          <i class="fas fa-user-circle"></i>{{user_info.name}}</div>
         </div>
        <div class="input-group sport-rwd">
          <input type="text" class="form-control" v-model="message" placeholder="紀錄運動燃燒卡洛里">
          <div class="input-group-append">
            <button type="button" class="btn btn-success" @click="submit"><i class="fas fa-search"></i>
            </button>
          </div>
        </div>
        <div class="col table-sm">
          <table v-if='search_status===true'  class="table table-hover table-striped" id="query-sport">
            <tr class="rwd-sport-query">
              <td colspan="2" width="120px"> 輸入運動時間:</td>
              <td  colspan="2"> <input class="input is-primary" v-model="min" type="number" placeholder="誠實的打下去"></td>
            </tr>
            <tr class="rwd-sport-query">
              <td colspan="2" width="120px"> 您的體重:</td>
              <td  colspan="2"> <input class="input is-danger"  v-model="weight" type="number" placeholder="不能說的秘密" disabled="disabled"></td>
            </tr>
          </table>
          <table v-if='search_status===true'  class="table table-hover table-striped" id="query-sport">
            <thead>
              <tr>
                <th colspan="4"><i class="fas fa-running"></i>  運動30分鐘所消耗熱量(60kg為例) 單位:大卡</th>
                <th class="sport-index" colspan="2"></th>
              </tr>
            </thead>
            <tbody>
              <tr class="title-sport sport-query-color">
                <td class="sport-index"> <i class="fas fa-list-alt"></i> </td>
                <td> 運動項目 </td>
                <td> 甩多少 </td>
                <td class="user-weight"> 體重   </td>
                <td class="user-sport-min"> 奮鬥時間</br>(分鐘) </td>
                <td> 預計成果 </td>
                <td class="query-sport-item" width="80px"> 記起來! </td>
              </tr>
              <tr v-for="(sport, idx) in sports" class="sport-query-data">
                <td class="sport-index">{{idx+1}}</td>
                <td class="sport-item">{{sport.name}}</td>
                <td >{{sport.consume_60kg}}</td>
                <td class="user-weight" width="80px"> <input class="input is-danger"  v-model="weight" type="number" placeholder="不能說的秘密" disabled="disabled"></td>
                <td class="user-sport-min" width="110px"> <input class="input is-primary" v-model="min" type="number" placeholder="誠實的打下去"></td>
                <td :keyup="consume">{{sport.computed}}</td>
                <td class="query-sport-item" width="80px" >
                  <button @click="sport_record(idx)"  class="button is-success is-small is-light"> <i class="fas fa-plus-circle"> </i></button>
                </td>
              </tr>
            </tbody>
            <tfoot>
              <td colspan="1"> </td>
              <th class="sport-index" colspan="3"></th>
              <td align="right" colspan="3"> <button @click="end_search" class="button is-danger is-small is-light">結束紀錄表</button></td>
            </tfoot>
          </table>
        </div>
      </div> 
      <div class="col-md-6 daily-record">
        <div class="row sport-record">
          <h2 class="title sport-record"> 今日運動紀錄狀態 <i class="far fa-clipboard"></i> </h2>
          <div v-if="member_status === true" class="daily_sport_status">
            <table class="control_fit_sport_record">
              <thead>
                <th colspan="3" scope="col"> ControlFit - 運動紀錄使用須知 <i class="far fa-comment-dots" @click="sport_user_guide"></i> </th>
               </thead>
              <tbody v-show="noticeshow === true">
                <tr>
                  <th> STEP1: </th>
                  <td> 請使用者先註冊或登入，並更新體重資訊。</td>
                </tr>
                <tr>
                  <th> STEP2: </th>
                  <td> 藉由搜尋列搜尋運動，並輸入運動分鐘加至每日記錄。</td>
                </tr>
                <tr>
                  <th> STEP3: </th>
                  <td> 若對登入紀錄有疑慮可直接編輯/刪除這筆紀錄資料。</td>
                </tr>
             </tbody>
            </table>
            <table class="table user-sport-info">
              <thead>
                <th  colspan="1" scope="col">  <i class="far fa-address-card"></i>  {{user_info.name}}</th>
                <th align="right" colspan="1" scope="col"> <i class="fas fa-clock"></i>:  {{currentTime}}</th>
                <th align="right" colspan="1" scope="col"> <i class="fas fa-calendar-day"></i> :  {{currentDay}}</th>
              </thead>
              <tbody>
                <tr>
                  <th scope="row"><i class="fas fa-clipboard-list"></i> : 今日運動紀錄</th>
                  <td>共 : {{daily_count}} 筆 </td>
                  <td>共燃燒: <i class="fas fa-fire sport_fire"></i>  {{daily_sum}} 大卡 
                    <button class="button is-link is-small is-light is-rounded" @click="more_record">  <i class="fas fa-comment-dots sport_more"></i>MORE</button>
                  </td>
                </tr>
              </tbody>
            </table>
            <table class="table user-sport-info rwd">
              <thead>
                <th  colspan="1" scope="col">  <i class="far fa-address-card"></i>  {{user_info.name}}</th>
                <th align="right" colspan="3" scope="col"> <i class="fas fa-clock"></i>:  {{currentTime}}</th>
              </thead>
              <tbody>
                <tr>
                  <th scope="row"><i class="fas fa-clipboard-list"></i> : 運動紀錄</th>
                  <td align="right"> {{daily_count}} 筆</td>
                </tr>
                <tr>
                  <th scope="row"><i class="fas fa-fire sport_fire"></i>  : 燃燒</th>
                  <td align="right"> {{daily_sum}} 大卡</td>
                </tr>
                <tfoot>
                  <td align="right" colspan="2"> <button class="button is-link is-small is-light is-rounded" @click="more_record">  <i class="fas fa-comment-dots sport_more"></i>MORE</button></td>
                </tfoot>
              </tbody>
            </table>
          </div>
          <div v-else class="daily_sport_status">
             <div class="sport-un-sign-status">
              <p> 親愛的使用者您好:</br>
                  您目前狀態 : <div class="un-sign-status">尚未註冊</div>或<div class="un-sign-status">登入</div>。</br>
                可以透過按下 <%= link_to "註冊", new_member_registration_path %> 
                或是 <%= link_to "登入", new_member_session_path %> 使用運動紀錄功能。
              </p>
              <table class="control_fit_sport_record">
                <thead>
                  <th colspan="3" scope="col"> ControlFit - 運動紀錄使用須知 <i class="far fa-comment-dots" @click="sport_user_guide"></i> </th>
                 </thead>
                <tbody v-show="noticeshow === true">
                  <tr>
                    <th> STEP1: </th>
                    <td> 請使用者先註冊或登入，並更新體重資訊。</td>
                  </tr>
                  <tr>
                    <th> STEP2: </th>
                    <td> 藉由搜尋列搜尋運動，並輸入運動分鐘加至每日記錄。</td>
                  </tr>
                  <tr>
                    <th> STEP3: </th>
                    <td> 若對登入紀錄有疑慮可直接編輯/刪除這筆紀錄資料。</td>
                  </tr>
               </tbody>
              </table>
             </div>
          </div>
          <div class="col actual-record">
            <table v-if="daily_record_status === true" class="table table-hover" id="record-sport">
              <thead>  
                <tr>
                  <th colspan="2"> <i class="fas fa-clipboard-list"></i> : 今日運動紀錄 </th>
                  <!-- <th class="sport-index" colspan="1"></th> -->
                  <th align="right" colspan="2"> <i class="far fa-grin-beam-sweat"></i> 總共燃燒 : <span class="total-calory">{{daily_sum}}</span> 大卡 </th>
                </tr>
              </thead>
              <tbody>  
                <tr class="sport-daily-reocrd">
                  <th class="sport-index"> # </th>
                  <th class="sport-record-time"> 紀錄時間 </th>
                  <th class="sport-item"> 運動項目 </th>
                  <th class="sport-time"> 奮鬥時間 </th>
                  <th class="sport-cousme"> 燃燒值   </th>
                  <th class="sport-honest"> 誠實豆沙包</th>
                </tr>
                <tr v-for="(record, index) in daily_sport" class="sport-daily-reocrd-cotent">
                  <td class="sport-index">{{index+1}}</td>
                  <td class="sport-record-time">{{record.created_at}}</td>
                  <td class="sport-item">{{record.name}}</td>
                  <td class="sport-time" v-if="editstatus[index] !== true">{{record.min}}</td>
                  <td class="sport-time" width="110px" v-else ><input class="input is-primary" v-model= "daily_sport[index].min" type="number" placeholder=""></td>
                  <td class="sport-cousme">{{record.totalconsum}}</td>
                  <td class="sport-honest" width="120px">
                    <button v-if="editstatus[index] === false"@click="edit_record(index)" class="button is-warning is-small is-light"> <i class="fas fa-pencil-alt"> </i></button>
                    <button v-if="editstatus[index] === true" @click="update_record(index)"class="button is-success is-small is-light"> <i class="fas fa-save"></i></button>
                    <button @click="delete_record(index)"class="button is-danger is-small is-light"> <i class="fas fa-trash"> </i></button>
                  </td>                 
                </tr>
              </tbody>
              <tfoot>
                  <td  class="sport-index" colspan="2"></td>
                  <td colspan="4"></td>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
      <div class="sportextend">

      </div>
    </div>
  </div>  
</section>



app/views/record_databases/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Daily record</title>
</head>
<body>
     <a href="">History record</a>
     <button type="button">Add New Record</button>
     <button type="button">Add New Food Record</button>
</body>
</html>