config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: {registrations: 'members/registrations' ,omniauth_callbacks: 'members/omniauth_callbacks' }
  resource :member, only: :show do
    member do
      get :following, :followers
      get :foodday,:foodmonth,:foodweek  # food record by day/week/month
      get :sportday,:sportmonth,:sportweek  # sport record by day/week/month
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :blogs  do 
    member do 
       patch :tdee   #/blog/:id/tdee
       get   :secret #/blog/:id/secret
    end
  end
  

  resources :records
  root 'records#index'
  resources :users
  resources :record_databases
  resources :exercise_records
  resources :food_records
  resources :demands


  post '/search_sport/favorite' => 'exercise_records#favorite', :as => 'favorite_exercise_record' 
  post '/search_food/favorite' => 'food_records#favorite', :as => 'favorite_food_record' 
  get '/search_sport/statistics' => 'exercise_records#statistics', :as => 'statistics_exercise_record'
  get '/search_food/statistics' => 'food_records#statistics', :as => 'statistics_food_record'
  get '/search_food' => 'record_databases#search_food', :as => 'search_food_record_database'
  get '/search_sport' => 'record_databases#search_sport', :as => 'search_sport_record_database'
  get '/search_food/random' => 'food_records#random', :as => 'random_food_record'
  get '/search_food/list' => 'food_records#list', :as => 'list_food_record'
end

app/views/shared/_footer.html.erb
<footer class="section footer">
  <div class="col-12 footers">
    <div class="footer-links">
      <a href="https://github.com/AstroCamp3rd-Demo/ControlFit"><i class="fab fa-github"></i></a>
    </div>
    <div class="footer-copyright">
      Copyright © 2020 健康管家公司 保留一切權利。
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb

<input type="checkbox" name="" id="navbar-control" aria-hidden="true">

<header class="section navbar">
  <nav class="navbars fixed-top navbar-expand-lg">
    <div class="container-fluid">
      <div class="row">
        <ul class="col navbar-header">
          <!-- 漢堡選單 -->
         <li class="navbar-togller-item bar-block">
           <label for="navbar-control" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false" aria-label="Toggle navigation">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </label>
         </li>
         <li class="navbar-togller-item logo-block">
          <a class="nav-link" href="<%= root_path %>" >
            <span><%= image_tag("brand05.png") %></span>
          </a>
         </li>
         <span class="navbar-togller-item login-block">
          <li class="nav-item">
            <% if member_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-plus"></i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <span class="d-block"><%= current_member.email %></span>
                <a rel="nofollow" data-method="get" href="<%= member_path %>", class="dropdown-item">個人資料</a>
                <a rel="nofollow" data-method="get" href="/members/edit", class="dropdown-item">修改資料</a>
                <div class="dropdown-divider"></div>  
                  <a rel="nofollow" data-method="delete" href="/members/sign_out", class="dropdown-item">登出</a>
              </div>
          </li>
            <% else %>
          <li class="nav-item sign-in">
            <a href="<%= new_member_session_path %>">登入</a>
          </li>
            <% end %>
         </span>
        </ul>
        <div class="logo">
          <a class="nav-link brand" href="<%= root_path %>" > 
            <span class="brand"><%= image_tag("brand05.png") %></span>
          </a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-main">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="<%= blogs_path %>">
                <span>認識自己</span>
               </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= search_food_record_database_path %>">
                <span>食品熱量</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href=" <%= search_sport_record_database_path %>">
                <span>運動消耗</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= users_path %>">
                <span>看看別人</span>
            </a>
            </li>
          </ul>
        </div>
        <div class="nav-link d-none d-sm-none d-md-block">
          <% if member_signed_in? %>
            <% if current_member.name? %>
              <%= link_to current_member.name, member_path, class:'text-info' %>
            <% else %>
              <%= link_to current_member.email, member_path, class:'text-info' %>
            <% end %>
          <% end %>
        </div>
        <ul class="navbar-actions">
          <% if member_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-plus"></i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <span class="d-block"><%= current_member.email %></span>
                  <%= link_to '個人資料', member_path, class:'dropdown-item'%>
                  <%= link_to '修改資料', edit_member_registration_path, class:'dropdown-item'%>
                <div class="dropdown-divider"></div>
                  <%= link_to '登出', destroy_member_session_path, method:'delete', class:'dropdown-item'%>
              </div>
            </li>
          <li class="nav-item">
          </li>
            <% else %>
          <li class="nav-item">
            <a href="<%= new_member_registration_path %>">註冊</a>
          </li>
          <li class="nav-item">
            <a href="<%= new_member_session_path %>">登入</a>
          </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_notice.html.erb
<div class="alert alert-danger" role="alert">
  <%= notice %>
</div>

app/views/shared/_states.html.erb
<% @member ||= current_member %>
<div class="community follow-states">
  <span class="following">
    <button type="button" class="btn bg-light following-btn" data-toggle="modal" data-target="#exampleModal">
      <%= @member.following.count %>
      追蹤中
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content follow-modal">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">追蹤中</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <% @following.each do |f| %>
              <li>
                <div class="following-image">
                  <% if f.cover_image.attached? %>
                    <%= image_tag f.cover_image.variant(resize_to_limit: [50, 50]), class: 'following-img rounded-circle' %>
                  <% else %>
                    <img src="https://picsum.photos/50/50/?random=12", class="rounded-circle">
                  <% end %>
                  <%= link_to f.name, user_path(f), class:'following-link' %>
                </div c>
              </li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </span>
  <span class="followers">
    <button type="button" class="btn bg-light following-btn" data-toggle="modal" data-target="#exampleModal1">
      <%= @member.followers.count %>
      粉絲
    </button>
    <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content follow-modal">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">粉絲</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <% @followers.each do |f| %>
              <li>
                <div class="followers-image">
                  <% if f.cover_image.attached? %>
                    <%= image_tag f.cover_image.variant(resize_to_limit: [50, 50]), class:'followers-img rounded-circle' %>
                  <% else %>
                    <img src="https://picsum.photos/50/50/?random=12", class="rounded-circle">
                  <% end %>
                  <%= link_to f.name, user_path(f), class:'following-link' %>
                </div>
              </li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </span>
</div>